### ISSUE TITLE
use here package to locate project root

### ISSUE THREAD

**Issue by beyondpie** [Winnie09/imputationBenchmark#1]
Hi,
I find this repo is quite useful for me as a reference.   Thank you very much!
I notice lots of the codes are using the absolute dir name, which might make the codes not that generalized.  Maybe you can use `here` package, which can locate the project root automatically, and then you use it to locate the relative path.

**Comment by Winnie09** [comment]
Thank you @beyondpie ! This is indeed a very good suggestion. I will try it!
