### ISSUE TITLE
For MAGIC downstream analysis.

### ISSUE THREAD

**Issue by millersan** [Winnie09/imputationBenchmark#2]
Hi,
I found the paper is very helpful! Thank you!
I'm a user of MAGIC packages. But I was confused about using MAGIC for downstream analysis. Could I use Wilcox to evaluate differentially expressed genes in MAGIC imputation data?
kind regard,
Miller

**Comment by Winnie09** [comment]
Hi,
Thank you for your interest in this work! I will try my best to help, and may I have a bit more information about the data? For example, is it sequenced in a droplet-based or plate-based platform; and how many samples (here a sample could refer to a patient or a healthy donor, so each sample has many single cells)? 
Regards,
Wenpin

**Comment by millersan** [comment]
Dear author,

Thank you for your reply! We used the 10X Genomics, so it sequenced in a droplet-based. We collected two healthy donor samples for pre-experiment. After using Seurat integrated vignette, the object contains 21398 features across 18728 cells. 
For the MAGIC, we using KrishnaswamyLab code with the Seurat object:
```
mm_magic<-magic(mm)
DefaultAssay(mm_magic)<-'MAGIC_integrated'
```
After MAGIC imputation, some marker genes result in more in line with the wet experimental results.
But I don't know whether I could use the MAGIC imputation matrix to calculate the DEG for different cell_clusters. 

Thank you!
Miller

**Comment by Winnie09** [comment]
Hi Miller,

MAGIC is among the top methods in terms of downstream analysis for UMI-based data, according to our systematic evaluation.  We also found substantial variability in the performance of the methods within each evaluation aspect.  I hope the figures 2, 3, and 6  in our manuscript (https://genomebiology.biomedcentral.com/track/pdf/10.1186/s13059-020-02132-x.pdf) contain more details for you to make a decision.  On page 7 of the manuscript, we also reported some observations about MAGIC in the evaluation.  Please feel free to open a new issue if you have any other questions. Thank you!

Best regards,
Wenpin
