### ISSUE TITLE
 how to prepare single cell input from multiple subjects as an input?

### ISSUE THREAD

**Issue by complexgenome** [Winnie09/imputationBenchmark#3]
Dear Winnie,

Thank you for providing code and congratulations on the paper
I am interested to use music/bisque for single-cell deconvolution on bulk RNA sequenced individuals.
The tutorial/methods require to prepare single-cell input where multiple subjects' data are present in it. I have .Rds file per subject for the single-cell. I am using publicly available datasets.

How do I prepare input object from these per-subject single-cell raw counts?

Sorry, this has nothing to do with your paper, however, there are no methods/tutorials on how they managed to pull this off.

best,
Sanjeev S

**Comment by Winnie09** [comment]
Hi Sanjeev,

Thank you! I am not familiar with music/bisque, but are you preparing the input objects for single-cell RNA-seq data imputation? If yes,  please refer to Supplementary Table S4 of our manuscript (https://genomebiology.biomedcentral.com/track/pdf/10.1186/s13059-020-02132-x.pdf). This table is a summary of all scRNA-seq imputation methods used in each
evaluation of this benchmark. The table includes the name of the method, input, output, pre-processing steps for
each method that we applied, the programming language, assumptions about the method, the download date,
software version number, and link to each software package. 

If you have multiple gene expression matrices each from a subject (e.g. a donor), you may concatenate the matrices to get a new matrix (e.g. cbind(gene by cell matrix1, gene by cell matrix2)). You might want to consider the batch effects when performing analysis on the concatenated matrix.

Best,
Wenpin
