### ISSUE TITLE
Running the code

### ISSUE THREAD

**Issue by Andresd45** [Winnie09/imputationBenchmark#4]
Hi Winnie,

Congrats for the paper, I really enjoyed it.
I was wondering how to use your code, for instance I would like to run **realDE_bulkdiff_code_loss/code/03_get_wilcox_fdr** or **realDE_bulkdiff_code_loss/code/04_bulk_sc_diffgene_overlap_wilcox**. But you are importing some RDS files, is there a way to get those?, or how those files should look like?.

Thanks

**Comment by Winnie09** [comment]
Hi Andreas,

Thank you!  I share the link of the Dropbox folder containing the files read in the two .R files you mentioned: https://www.dropbox.com/sh/zztcqfnx9nhth4u/AAAx14KLezX6dBEzR9M8aKXZa?dl=0

Please let me know if this helps. 

Best,
Wenpin
